
# This file is automatically generated, you probably don't want to edit this

checkOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "checkOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL, ...) {

            super$initialize(
                package="metaumbrella",
                name="check",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)

            self$.addOption(private$..vars)
        }),
    active = list(
        vars = function() private$..vars$value),
    private = list(
        ..vars = NA)
)

checkResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "checkResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        checktable = function() private$.items[["checktable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Errors and warnings")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="checktable",
                title="List of problematic rows (if any)",
                rows=1,
                columns=list(
                    list(
                        `name`="Row", 
                        `type`="text"),
                    list(
                        `name`="Type_errors", 
                        `type`="text"),
                    list(
                        `name`="Description_errors", 
                        `type`="text"),
                    list(
                        `name`="author", 
                        `type`="text"),
                    list(
                        `name`="year", 
                        `type`="text"))))}))

checkBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "checkBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "metaumbrella",
                name = "check",
                version = c(1,0,0),
                options = options,
                results = checkResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Check dataset formatting
#'
#' 
#' @param data .
#' @param vars .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$checktable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$checktable$asDF}
#'
#' \code{as.data.frame(results$checktable)}
#'
#' @export
check <- function(
    data,
    vars) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("check requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- checkOptions$new(
        vars = vars)

    analysis <- checkClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

