
# This file is automatically generated, you probably don't want to edit this

umbrellaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "umbrellaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            method.var = "REML",
            true_effect = "largest",
            mult.level = FALSE,
            r = 0.5, ...) {

            super$initialize(
                package="metaumbrella",
                name="umbrella",
                requiresData=TRUE,
                ...)

            private$..method.var <- jmvcore::OptionList$new(
                "method.var",
                method.var,
                options=list(
                    "REML",
                    "DL",
                    "hksj",
                    "ML",
                    "PM"),
                default="REML")
            private$..true_effect <- jmvcore::OptionList$new(
                "true_effect",
                true_effect,
                options=list(
                    "largest",
                    "pooled"),
                default="largest")
            private$..mult.level <- jmvcore::OptionBool$new(
                "mult.level",
                mult.level,
                default=FALSE)
            private$..r <- jmvcore::OptionNumber$new(
                "r",
                r,
                min=0,
                max=1,
                default=0.5)

            self$.addOption(private$..method.var)
            self$.addOption(private$..true_effect)
            self$.addOption(private$..mult.level)
            self$.addOption(private$..r)
        }),
    active = list(
        method.var = function() private$..method.var$value,
        true_effect = function() private$..true_effect$value,
        mult.level = function() private$..mult.level$value,
        r = function() private$..r$value),
    private = list(
        ..method.var = NA,
        ..true_effect = NA,
        ..mult.level = NA,
        ..r = NA)
)

umbrellaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "umbrellaResults",
    inherit = jmvcore::Group,
    active = list(
        umbrellatable = function() private$.items[["umbrellatable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Results of your umbrella review")
            self$add(jmvcore::Table$new(
                options=options,
                name="umbrellatable",
                title="a try to build a table",
                rows=1,
                columns=list(
                    list(
                        `name`="col1", 
                        `type`="text"),
                    list(
                        `name`="col2", 
                        `type`="text"),
                    list(
                        `name`="col3", 
                        `type`="text"))))}))

umbrellaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "umbrellaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "metaumbrella",
                name = "umbrella",
                version = c(1,0,0),
                options = options,
                results = umbrellaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Results of your umbrella review
#'
#' 
#' @param data .
#' @param method.var .
#' @param true_effect .
#' @param mult.level .
#' @param r .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$umbrellatable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$umbrellatable$asDF}
#'
#' \code{as.data.frame(results$umbrellatable)}
#'
#' @export
umbrella <- function(
    data,
    method.var = "REML",
    true_effect = "largest",
    mult.level = FALSE,
    r = 0.5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("umbrella requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- umbrellaOptions$new(
        method.var = method.var,
        true_effect = true_effect,
        mult.level = mult.level,
        r = r)

    analysis <- umbrellaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

