
# This file is automatically generated, you probably don't want to edit this

umbrellaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "umbrellaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            criteria = "Ioannidis",
            method.var = "REML",
            pre_post_cor = 0.8,
            true_effect = "largest",
            method.esb = "TESSPSST",
            mult.level = FALSE,
            r = 0.8,
            n_studies_1 = NULL,
            n_studies_2 = NULL,
            n_studies_3 = NULL,
            n_studies_4 = NULL,
            total_n_1 = NULL,
            total_n_2 = NULL,
            total_n_3 = NULL,
            total_n_4 = NULL,
            n_cases_1 = NULL,
            n_cases_2 = NULL,
            n_cases_3 = NULL,
            n_cases_4 = NULL,
            p_value_1 = NULL,
            p_value_2 = NULL,
            p_value_3 = NULL,
            p_value_4 = NULL,
            I2_1 = NULL,
            I2_2 = NULL,
            I2_3 = NULL,
            I2_4 = NULL,
            imprecision_1 = NULL,
            imprecision_2 = NULL,
            imprecision_3 = NULL,
            imprecision_4 = NULL,
            rob_1 = NULL,
            rob_2 = NULL,
            rob_3 = NULL,
            rob_4 = NULL,
            amstar_1 = NULL,
            amstar_2 = NULL,
            amstar_3 = NULL,
            amstar_4 = NULL,
            egger_p_1 = NULL,
            egger_p_2 = NULL,
            egger_p_3 = NULL,
            egger_p_4 = NULL,
            esb_p_1 = NULL,
            esb_p_2 = NULL,
            esb_p_3 = NULL,
            esb_p_4 = NULL,
            JK_p_1 = NULL,
            JK_p_2 = NULL,
            JK_p_3 = NULL,
            JK_p_4 = NULL,
            pi_1 = FALSE,
            pi_2 = FALSE,
            pi_3 = FALSE,
            pi_4 = FALSE,
            largest_CI_1 = FALSE,
            largest_CI_2 = FALSE,
            largest_CI_3 = FALSE,
            largest_CI_4 = FALSE,
            measure_forest = "eG",
            class_forest = "no_rest",
            title_forest = NULL,
            title_xaxis = NULL,
            cex = 1,
            cex_dot = 1,
            x_lim_adj = 0,
            y_lim_adj = 0,
            max_x = NULL,
            x_axis_adj = 0, ...) {

            super$initialize(
                package="metaumbrella",
                name="umbrella",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..criteria <- jmvcore::OptionList$new(
                "criteria",
                criteria,
                options=list(
                    "Ioannidis",
                    "GRADE",
                    "Personalized",
                    "None"),
                default="Ioannidis")
            private$..method.var <- jmvcore::OptionList$new(
                "method.var",
                method.var,
                options=list(
                    "REML",
                    "DL",
                    "hksj",
                    "ML",
                    "PM",
                    "FE"),
                default="REML")
            private$..pre_post_cor <- jmvcore::OptionNumber$new(
                "pre_post_cor",
                pre_post_cor,
                min=0,
                max=1,
                default=0.8)
            private$..true_effect <- jmvcore::OptionList$new(
                "true_effect",
                true_effect,
                options=list(
                    "largest",
                    "pooled"),
                default="largest")
            private$..method.esb <- jmvcore::OptionList$new(
                "method.esb",
                method.esb,
                options=list(
                    "IT.binom",
                    "IT.chisq",
                    "TESS",
                    "PSST",
                    "TESSPSST"),
                default="TESSPSST")
            private$..mult.level <- jmvcore::OptionBool$new(
                "mult.level",
                mult.level,
                default=FALSE)
            private$..r <- jmvcore::OptionNumber$new(
                "r",
                r,
                min=0,
                max=1,
                default=0.8)
            private$..n_studies_1 <- jmvcore::OptionString$new(
                "n_studies_1",
                n_studies_1)
            private$..n_studies_2 <- jmvcore::OptionString$new(
                "n_studies_2",
                n_studies_2)
            private$..n_studies_3 <- jmvcore::OptionString$new(
                "n_studies_3",
                n_studies_3)
            private$..n_studies_4 <- jmvcore::OptionString$new(
                "n_studies_4",
                n_studies_4)
            private$..total_n_1 <- jmvcore::OptionString$new(
                "total_n_1",
                total_n_1)
            private$..total_n_2 <- jmvcore::OptionString$new(
                "total_n_2",
                total_n_2)
            private$..total_n_3 <- jmvcore::OptionString$new(
                "total_n_3",
                total_n_3)
            private$..total_n_4 <- jmvcore::OptionString$new(
                "total_n_4",
                total_n_4)
            private$..n_cases_1 <- jmvcore::OptionString$new(
                "n_cases_1",
                n_cases_1)
            private$..n_cases_2 <- jmvcore::OptionString$new(
                "n_cases_2",
                n_cases_2)
            private$..n_cases_3 <- jmvcore::OptionString$new(
                "n_cases_3",
                n_cases_3)
            private$..n_cases_4 <- jmvcore::OptionString$new(
                "n_cases_4",
                n_cases_4)
            private$..p_value_1 <- jmvcore::OptionString$new(
                "p_value_1",
                p_value_1)
            private$..p_value_2 <- jmvcore::OptionString$new(
                "p_value_2",
                p_value_2)
            private$..p_value_3 <- jmvcore::OptionString$new(
                "p_value_3",
                p_value_3)
            private$..p_value_4 <- jmvcore::OptionString$new(
                "p_value_4",
                p_value_4)
            private$..I2_1 <- jmvcore::OptionString$new(
                "I2_1",
                I2_1)
            private$..I2_2 <- jmvcore::OptionString$new(
                "I2_2",
                I2_2)
            private$..I2_3 <- jmvcore::OptionString$new(
                "I2_3",
                I2_3)
            private$..I2_4 <- jmvcore::OptionString$new(
                "I2_4",
                I2_4)
            private$..imprecision_1 <- jmvcore::OptionString$new(
                "imprecision_1",
                imprecision_1)
            private$..imprecision_2 <- jmvcore::OptionString$new(
                "imprecision_2",
                imprecision_2)
            private$..imprecision_3 <- jmvcore::OptionString$new(
                "imprecision_3",
                imprecision_3)
            private$..imprecision_4 <- jmvcore::OptionString$new(
                "imprecision_4",
                imprecision_4)
            private$..rob_1 <- jmvcore::OptionString$new(
                "rob_1",
                rob_1)
            private$..rob_2 <- jmvcore::OptionString$new(
                "rob_2",
                rob_2)
            private$..rob_3 <- jmvcore::OptionString$new(
                "rob_3",
                rob_3)
            private$..rob_4 <- jmvcore::OptionString$new(
                "rob_4",
                rob_4)
            private$..amstar_1 <- jmvcore::OptionString$new(
                "amstar_1",
                amstar_1)
            private$..amstar_2 <- jmvcore::OptionString$new(
                "amstar_2",
                amstar_2)
            private$..amstar_3 <- jmvcore::OptionString$new(
                "amstar_3",
                amstar_3)
            private$..amstar_4 <- jmvcore::OptionString$new(
                "amstar_4",
                amstar_4)
            private$..egger_p_1 <- jmvcore::OptionString$new(
                "egger_p_1",
                egger_p_1)
            private$..egger_p_2 <- jmvcore::OptionString$new(
                "egger_p_2",
                egger_p_2)
            private$..egger_p_3 <- jmvcore::OptionString$new(
                "egger_p_3",
                egger_p_3)
            private$..egger_p_4 <- jmvcore::OptionString$new(
                "egger_p_4",
                egger_p_4)
            private$..esb_p_1 <- jmvcore::OptionString$new(
                "esb_p_1",
                esb_p_1)
            private$..esb_p_2 <- jmvcore::OptionString$new(
                "esb_p_2",
                esb_p_2)
            private$..esb_p_3 <- jmvcore::OptionString$new(
                "esb_p_3",
                esb_p_3)
            private$..esb_p_4 <- jmvcore::OptionString$new(
                "esb_p_4",
                esb_p_4)
            private$..JK_p_1 <- jmvcore::OptionString$new(
                "JK_p_1",
                JK_p_1)
            private$..JK_p_2 <- jmvcore::OptionString$new(
                "JK_p_2",
                JK_p_2)
            private$..JK_p_3 <- jmvcore::OptionString$new(
                "JK_p_3",
                JK_p_3)
            private$..JK_p_4 <- jmvcore::OptionString$new(
                "JK_p_4",
                JK_p_4)
            private$..pi_1 <- jmvcore::OptionBool$new(
                "pi_1",
                pi_1,
                default=FALSE)
            private$..pi_2 <- jmvcore::OptionBool$new(
                "pi_2",
                pi_2,
                default=FALSE)
            private$..pi_3 <- jmvcore::OptionBool$new(
                "pi_3",
                pi_3,
                default=FALSE)
            private$..pi_4 <- jmvcore::OptionBool$new(
                "pi_4",
                pi_4,
                default=FALSE)
            private$..largest_CI_1 <- jmvcore::OptionBool$new(
                "largest_CI_1",
                largest_CI_1,
                default=FALSE)
            private$..largest_CI_2 <- jmvcore::OptionBool$new(
                "largest_CI_2",
                largest_CI_2,
                default=FALSE)
            private$..largest_CI_3 <- jmvcore::OptionBool$new(
                "largest_CI_3",
                largest_CI_3,
                default=FALSE)
            private$..largest_CI_4 <- jmvcore::OptionBool$new(
                "largest_CI_4",
                largest_CI_4,
                default=FALSE)
            private$..measure_forest <- jmvcore::OptionList$new(
                "measure_forest",
                measure_forest,
                options=list(
                    "eG",
                    "eOR"),
                default="eG")
            private$..class_forest <- jmvcore::OptionList$new(
                "class_forest",
                class_forest,
                options=list(
                    "no_rest",
                    "I",
                    "II",
                    "III",
                    "IV",
                    "High",
                    "Moderate",
                    "Low"),
                default="no_rest")
            private$..title_forest <- jmvcore::OptionString$new(
                "title_forest",
                title_forest)
            private$..title_xaxis <- jmvcore::OptionString$new(
                "title_xaxis",
                title_xaxis)
            private$..cex <- jmvcore::OptionNumber$new(
                "cex",
                cex,
                min=0,
                default=1)
            private$..cex_dot <- jmvcore::OptionNumber$new(
                "cex_dot",
                cex_dot,
                min=0,
                default=1)
            private$..x_lim_adj <- jmvcore::OptionNumber$new(
                "x_lim_adj",
                x_lim_adj,
                default=0)
            private$..y_lim_adj <- jmvcore::OptionNumber$new(
                "y_lim_adj",
                y_lim_adj,
                default=0)
            private$..max_x <- jmvcore::OptionString$new(
                "max_x",
                max_x)
            private$..x_axis_adj <- jmvcore::OptionNumber$new(
                "x_axis_adj",
                x_axis_adj,
                default=0)

            self$.addOption(private$..vars)
            self$.addOption(private$..criteria)
            self$.addOption(private$..method.var)
            self$.addOption(private$..pre_post_cor)
            self$.addOption(private$..true_effect)
            self$.addOption(private$..method.esb)
            self$.addOption(private$..mult.level)
            self$.addOption(private$..r)
            self$.addOption(private$..n_studies_1)
            self$.addOption(private$..n_studies_2)
            self$.addOption(private$..n_studies_3)
            self$.addOption(private$..n_studies_4)
            self$.addOption(private$..total_n_1)
            self$.addOption(private$..total_n_2)
            self$.addOption(private$..total_n_3)
            self$.addOption(private$..total_n_4)
            self$.addOption(private$..n_cases_1)
            self$.addOption(private$..n_cases_2)
            self$.addOption(private$..n_cases_3)
            self$.addOption(private$..n_cases_4)
            self$.addOption(private$..p_value_1)
            self$.addOption(private$..p_value_2)
            self$.addOption(private$..p_value_3)
            self$.addOption(private$..p_value_4)
            self$.addOption(private$..I2_1)
            self$.addOption(private$..I2_2)
            self$.addOption(private$..I2_3)
            self$.addOption(private$..I2_4)
            self$.addOption(private$..imprecision_1)
            self$.addOption(private$..imprecision_2)
            self$.addOption(private$..imprecision_3)
            self$.addOption(private$..imprecision_4)
            self$.addOption(private$..rob_1)
            self$.addOption(private$..rob_2)
            self$.addOption(private$..rob_3)
            self$.addOption(private$..rob_4)
            self$.addOption(private$..amstar_1)
            self$.addOption(private$..amstar_2)
            self$.addOption(private$..amstar_3)
            self$.addOption(private$..amstar_4)
            self$.addOption(private$..egger_p_1)
            self$.addOption(private$..egger_p_2)
            self$.addOption(private$..egger_p_3)
            self$.addOption(private$..egger_p_4)
            self$.addOption(private$..esb_p_1)
            self$.addOption(private$..esb_p_2)
            self$.addOption(private$..esb_p_3)
            self$.addOption(private$..esb_p_4)
            self$.addOption(private$..JK_p_1)
            self$.addOption(private$..JK_p_2)
            self$.addOption(private$..JK_p_3)
            self$.addOption(private$..JK_p_4)
            self$.addOption(private$..pi_1)
            self$.addOption(private$..pi_2)
            self$.addOption(private$..pi_3)
            self$.addOption(private$..pi_4)
            self$.addOption(private$..largest_CI_1)
            self$.addOption(private$..largest_CI_2)
            self$.addOption(private$..largest_CI_3)
            self$.addOption(private$..largest_CI_4)
            self$.addOption(private$..measure_forest)
            self$.addOption(private$..class_forest)
            self$.addOption(private$..title_forest)
            self$.addOption(private$..title_xaxis)
            self$.addOption(private$..cex)
            self$.addOption(private$..cex_dot)
            self$.addOption(private$..x_lim_adj)
            self$.addOption(private$..y_lim_adj)
            self$.addOption(private$..max_x)
            self$.addOption(private$..x_axis_adj)
        }),
    active = list(
        vars = function() private$..vars$value,
        criteria = function() private$..criteria$value,
        method.var = function() private$..method.var$value,
        pre_post_cor = function() private$..pre_post_cor$value,
        true_effect = function() private$..true_effect$value,
        method.esb = function() private$..method.esb$value,
        mult.level = function() private$..mult.level$value,
        r = function() private$..r$value,
        n_studies_1 = function() private$..n_studies_1$value,
        n_studies_2 = function() private$..n_studies_2$value,
        n_studies_3 = function() private$..n_studies_3$value,
        n_studies_4 = function() private$..n_studies_4$value,
        total_n_1 = function() private$..total_n_1$value,
        total_n_2 = function() private$..total_n_2$value,
        total_n_3 = function() private$..total_n_3$value,
        total_n_4 = function() private$..total_n_4$value,
        n_cases_1 = function() private$..n_cases_1$value,
        n_cases_2 = function() private$..n_cases_2$value,
        n_cases_3 = function() private$..n_cases_3$value,
        n_cases_4 = function() private$..n_cases_4$value,
        p_value_1 = function() private$..p_value_1$value,
        p_value_2 = function() private$..p_value_2$value,
        p_value_3 = function() private$..p_value_3$value,
        p_value_4 = function() private$..p_value_4$value,
        I2_1 = function() private$..I2_1$value,
        I2_2 = function() private$..I2_2$value,
        I2_3 = function() private$..I2_3$value,
        I2_4 = function() private$..I2_4$value,
        imprecision_1 = function() private$..imprecision_1$value,
        imprecision_2 = function() private$..imprecision_2$value,
        imprecision_3 = function() private$..imprecision_3$value,
        imprecision_4 = function() private$..imprecision_4$value,
        rob_1 = function() private$..rob_1$value,
        rob_2 = function() private$..rob_2$value,
        rob_3 = function() private$..rob_3$value,
        rob_4 = function() private$..rob_4$value,
        amstar_1 = function() private$..amstar_1$value,
        amstar_2 = function() private$..amstar_2$value,
        amstar_3 = function() private$..amstar_3$value,
        amstar_4 = function() private$..amstar_4$value,
        egger_p_1 = function() private$..egger_p_1$value,
        egger_p_2 = function() private$..egger_p_2$value,
        egger_p_3 = function() private$..egger_p_3$value,
        egger_p_4 = function() private$..egger_p_4$value,
        esb_p_1 = function() private$..esb_p_1$value,
        esb_p_2 = function() private$..esb_p_2$value,
        esb_p_3 = function() private$..esb_p_3$value,
        esb_p_4 = function() private$..esb_p_4$value,
        JK_p_1 = function() private$..JK_p_1$value,
        JK_p_2 = function() private$..JK_p_2$value,
        JK_p_3 = function() private$..JK_p_3$value,
        JK_p_4 = function() private$..JK_p_4$value,
        pi_1 = function() private$..pi_1$value,
        pi_2 = function() private$..pi_2$value,
        pi_3 = function() private$..pi_3$value,
        pi_4 = function() private$..pi_4$value,
        largest_CI_1 = function() private$..largest_CI_1$value,
        largest_CI_2 = function() private$..largest_CI_2$value,
        largest_CI_3 = function() private$..largest_CI_3$value,
        largest_CI_4 = function() private$..largest_CI_4$value,
        measure_forest = function() private$..measure_forest$value,
        class_forest = function() private$..class_forest$value,
        title_forest = function() private$..title_forest$value,
        title_xaxis = function() private$..title_xaxis$value,
        cex = function() private$..cex$value,
        cex_dot = function() private$..cex_dot$value,
        x_lim_adj = function() private$..x_lim_adj$value,
        y_lim_adj = function() private$..y_lim_adj$value,
        max_x = function() private$..max_x$value,
        x_axis_adj = function() private$..x_axis_adj$value),
    private = list(
        ..vars = NA,
        ..criteria = NA,
        ..method.var = NA,
        ..pre_post_cor = NA,
        ..true_effect = NA,
        ..method.esb = NA,
        ..mult.level = NA,
        ..r = NA,
        ..n_studies_1 = NA,
        ..n_studies_2 = NA,
        ..n_studies_3 = NA,
        ..n_studies_4 = NA,
        ..total_n_1 = NA,
        ..total_n_2 = NA,
        ..total_n_3 = NA,
        ..total_n_4 = NA,
        ..n_cases_1 = NA,
        ..n_cases_2 = NA,
        ..n_cases_3 = NA,
        ..n_cases_4 = NA,
        ..p_value_1 = NA,
        ..p_value_2 = NA,
        ..p_value_3 = NA,
        ..p_value_4 = NA,
        ..I2_1 = NA,
        ..I2_2 = NA,
        ..I2_3 = NA,
        ..I2_4 = NA,
        ..imprecision_1 = NA,
        ..imprecision_2 = NA,
        ..imprecision_3 = NA,
        ..imprecision_4 = NA,
        ..rob_1 = NA,
        ..rob_2 = NA,
        ..rob_3 = NA,
        ..rob_4 = NA,
        ..amstar_1 = NA,
        ..amstar_2 = NA,
        ..amstar_3 = NA,
        ..amstar_4 = NA,
        ..egger_p_1 = NA,
        ..egger_p_2 = NA,
        ..egger_p_3 = NA,
        ..egger_p_4 = NA,
        ..esb_p_1 = NA,
        ..esb_p_2 = NA,
        ..esb_p_3 = NA,
        ..esb_p_4 = NA,
        ..JK_p_1 = NA,
        ..JK_p_2 = NA,
        ..JK_p_3 = NA,
        ..JK_p_4 = NA,
        ..pi_1 = NA,
        ..pi_2 = NA,
        ..pi_3 = NA,
        ..pi_4 = NA,
        ..largest_CI_1 = NA,
        ..largest_CI_2 = NA,
        ..largest_CI_3 = NA,
        ..largest_CI_4 = NA,
        ..measure_forest = NA,
        ..class_forest = NA,
        ..title_forest = NA,
        ..title_xaxis = NA,
        ..cex = NA,
        ..cex_dot = NA,
        ..x_lim_adj = NA,
        ..y_lim_adj = NA,
        ..max_x = NA,
        ..x_axis_adj = NA)
)

umbrellaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "umbrellaResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        checktable = function() private$.items[["checktable"]],
        strattable = function() private$.items[["strattable"]],
        metatable = function() private$.items[["metatable"]],
        addtable = function() private$.items[["addtable"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Results of the umbrella review")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text"))
            self$add(jmvcore::Table$new(
                options=options,
                name="checktable",
                title="List of problematic rows (if any)",
                rows=1,
                columns=list(
                    list(
                        `name`="Row", 
                        `type`="text"),
                    list(
                        `name`="Type_errors", 
                        `type`="text"),
                    list(
                        `name`="Description_errors", 
                        `type`="text"),
                    list(
                        `name`="author", 
                        `type`="text"),
                    list(
                        `name`="year", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="strattable",
                title="Summary results",
                rows=1,
                columns=list(
                    list(
                        `name`="Factor", 
                        `type`="text"),
                    list(
                        `name`="Criteria", 
                        `type`="text"),
                    list(
                        `name`="Class", 
                        `type`="text"),
                    list(
                        `name`="n_studies", 
                        `type`="text"),
                    list(
                        `name`="total_n", 
                        `type`="text"),
                    list(
                        `name`="n_cases", 
                        `type`="text"),
                    list(
                        `name`="n_controls", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="metatable",
                title="Core meta-analytic results",
                rows=1,
                columns=list(
                    list(
                        `name`="Factor", 
                        `type`="text"),
                    list(
                        `name`="measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `type`="text"),
                    list(
                        `name`="value_CI", 
                        `type`="text"),
                    list(
                        `name`="eG", 
                        `type`="text"),
                    list(
                        `name`="eG_CI", 
                        `type`="text"),
                    list(
                        `name`="eOR", 
                        `type`="text"),
                    list(
                        `name`="eOR_CI", 
                        `type`="text"),
                    list(
                        `name`="p_value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="addtable",
                title="Additional results",
                rows=1,
                columns=list(
                    list(
                        `name`="Factor", 
                        `type`="text"),
                    list(
                        `name`="I2", 
                        `type`="text"),
                    list(
                        `name`="PI_eG", 
                        `type`="text"),
                    list(
                        `name`="PI_eOR", 
                        `type`="text"),
                    list(
                        `name`="egger_p", 
                        `type`="text"),
                    list(
                        `name`="ESB_p", 
                        `type`="text"),
                    list(
                        `name`="power_med", 
                        `type`="text"),
                    list(
                        `name`="JK_p", 
                        `type`="text"),
                    list(
                        `name`="largest_CI_eG", 
                        `type`="text"),
                    list(
                        `name`="largest_CI_eOR", 
                        `type`="text"),
                    list(
                        `name`="rob", 
                        `type`="text"),
                    list(
                        `name`="amstar", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                width=100,
                height=100,
                renderFun=".plot"))}))

umbrellaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "umbrellaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "metaumbrella",
                name = "umbrella",
                version = c(1,0,0),
                options = options,
                results = umbrellaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

